### ISSUE TITLE
Vue3 compatibility

### ISSUE THREAD

**Issue by simonbuehler** [ankurk91/laravel-form-validation#5]
hi,

it would be awesome if the breaking changes in registering the plugin could be fixed for a vue3 version 

e.g. around https://github.com/ankurk91/laravel-form-validation/blob/f10550e2464b28bb80a276de6ffba53b52a59daf/src/index.ts#L9  - new global api:  https://v3.vuejs.org/guide/migration/global-api.html#a-new-global-api-createapp

**Comment by ankurk91** [comment]
https://v3.vuejs.org/guide/plugins.html#writing-a-plugin

Plugins can specify an `install` method and vue.js will pass the current app instance to callback method

Here is the example taken from docs.
```js
// plugins/i18n.js
export default {
  install: (app, options) => {
    // Plugin code goes here
  }
}
```
Here is my actual code take from master branch 
```ts
const VueFormPlugin = {
  install(Vue: App) {
    Vue.directive('invalid', IsInvalidDirective);
    Vue.component('field-error', FieldErrorComponent);
  }
}
```

Dont get confused by the variable name `App` here. It is TS code.

Hope this is clear to you now.

**Comment by simonbuehler** [comment]
Ok i upgraded to vue3 and it works, somehow the error validation Errors are not shown when using in composition api component but this may be another issue I'll k look into

**Comment by ankurk91** [comment]
I haven't tried the composition api. (hate react) 😅

But if you will share an example, I will debug for sure.

**Comment by simonbuehler** [comment]
ok, my mistake, maybe this could be added to the docs for usage with composition api:

```javascript

setup(props) {
    const foo = {
        bar: ''
    };
    const form = ref(new Form()); //ref for reactivity

    function submit() {
        form.value.patch('/api/XXX', foo).then( //use composition-api style value
            //ok
        ).catch(error => {
            //error
        });
    }
    return {
        foo,
        form,
        submit,
    };
},
